server:
  port: 9999

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Farrux5200/MarketPlace-configuration
          username: Farrux5200
          password: ${git.password}
        default-label: develop